%% Convert ROAST MESH to Voxels
% Created by Alejandro Albizu on 11/07/2021
% Last Updated: 11/07/2021 by AA
clear

% Settings
%--------------------------
rootDir = '/blue/camctrp/working/Alejandro/toolboxes/roast-3.0';
subs = [9051 9021 9023 9031 9032 9047 9054];
email = 'alexanderalbizu@ufl.edu';
arySize = 6401360;
MaxArraySize = 3000;
%--------------------------

tic
for a = 1:round(arySize/MaxArraySize)
    tic
    disp(['Starting Batch-' num2str(a) '...'])
    tmpfile = fullfile(rootDir,['tmp_sbatch' num2str(a) '.txt']);
    fi = fopen(tmpfile, 'w');
    sbatch = fprintf(fi,['#!/bin/bash\n',...
        '#SBATCH --job-name=tdcsDose\n',...
        '#SBATCH --mail-user=%s\n',...
        '#SBATCH --mail-type=ALL\n',...
        '#SBATCH --output=PREC_%%A-%%a.log\n',...
        '#SBATCH --ntasks=1\n',...
        '#SBATCH --mem=10gb\n',...
        '#SBATCH --account=camctrp\n',...
        '#SBATCH --qos=camctrp-b\n',... 
        '##SBATCH --distribution=cyclic:cyclic\n',...
        '##SBATCH --partition=gpu\n',...
        '##SBATCH --gres=gpu:a100:4\n',...
        '#SBATCH --time=48:00:00\n',...
        '#SBATCH --array=1-%s%%800\n',...
        '\n',...
        'ml matlab/2017b\n',...
        'echo ARRAY ID: $SLURM_ARRAY_TASK_ID\n',...
        'idx=$((${SLURM_ARRAY_TASK_ID}+%s))\n',...
        'sub=(' num2str(subs) ')\n',...
        '/blue/camctrp/working/Alejandro/toolboxes/roast-3.0/exhaustiveSearch_XL $sub $idx\n',...
        ],email,num2str(MaxArraySize),num2str(MaxArraySize*(a-1))); fclose(fi);
    cmd = sprintf('sbatch %s',tmpfile); system(cmd);  % SBATCH
    
    % WAIT UNTIL CURRENT SBATCH COMPLETE
    running = 1;
    while running 
        [~,queue] = system('squeue -A camctrp'); % Check HPG queue
        running = contains(queue,'tdcsDose'); pause(1); 
    end
    
    % Remove TMP files
    delete(tmpfile); system('rm PREC*'); 
    toc
end
toc